name: eosdart_hyperion
description: EOSIO-based blockchain RPC Hyperion API client for Dart and Flutter applications.
version: 0.0.1
author: Javier Mendonça <javier@eossweden.org>
homepage: https://github.com/eosswedenorg/eosdart_hyperion

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  chopper: ^3.0.1+1
  eosdart_ecc: ^0.4.0
  pedantic: ^1.9.0
  json_annotation: ^3.0.1
  equatable: ^1.1.0

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  chopper_generator: ^3.0.3
  json_serializable: ^3.2.3